language : cpp

compiler :
  - gcc
  
before_install:
  - echo $LANG
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libopencv-dev
  - sudo apt-get install libudev-dev
  - sudo apt-get install libglib2.0-dev
  - sudo apt-get install libssl-dev
  - sudo apt-get install libcrypto++-dev
  - sudo apt-get install libcfitsio3-dev
  - sudo apt-get install libv4l-dev
  - sudo apt-get install intltool gtk-doc-tools autoconf 
  - wget https://github.com/GNOME/aravis/archive/ARAVIS_0_3_7.tar.gz
  - tar -xvf ARAVIS_0_3_7.tar.gz
  - cd aravis-ARAVIS_0_3_7 && sh autogen.sh && ./configure 
  - sudo make install
  - ls
  - cd ..
  - ls
  
os : 
  - linux 
